interface MusicTrack {
  trackId: string;
  title: string;
  coverSrc: string;
  mp3Url: string;
  wavUrl: string;
}

export const tracks: MusicTrack[] = [
  {
    trackId: "doremi",
    title: "До Ре Мі",
    coverSrc: "/images/music/doremi.jpeg",
    mp3Url: "/music/doremi.mp3",
    wavUrl: "/music/doremi.wav",
  },
  {
    trackId: "zabka",
    title: "Жабка",
    coverSrc: "/images/music/zabka.jpeg",
    mp3Url: "/music/zabka.mp3",
    wavUrl: "/music/zabka.wav",
  },
  {
    trackId: "lito",
    title: "Літо",
    coverSrc: "/images/music/lito.png",
    mp3Url: "/music/lito.mp3",
    wavUrl: "/music/lito.wav",
  },
  {
    trackId: "buldozer",
    title: "Їде Бульдозер",
    coverSrc: "/images/music/buldozer.jpeg",
    mp3Url: "/music/buldozer.mp3",
    wavUrl: "/music/buldozer.wav",
  },
  {
    trackId: "cosmos",
    title: "Космос",
    coverSrc: "/images/music/cosmos.jpeg",
    mp3Url: "/music/cosmos.mp3",
    wavUrl: "/music/cosmos.wav",
  },
  {
    trackId: "twaryny",
    title: "Що їдять тварини",
    coverSrc: "/images/music/tvaryny.jpeg",
    mp3Url: "/music/twaryny.mp3",
    wavUrl: "/music/twaryny.wav",
  },
  {
    trackId: "dino",
    title: "Динозаври",
    coverSrc: "/images/music/dino.jpeg",
    mp3Url: "/music/dino.mp3",
    wavUrl: "/music/dino.wav",
  },
  {
    trackId: "kolyskova",
    title: "Колискова",
    coverSrc: "/images/music/kolyskova.jpeg",
    mp3Url: "/music/kolyskova.mp3",
    wavUrl: "/music/kolyskova.wav",
  },
  {
    trackId: "ovochi",
    title: "Овочі",
    coverSrc: "/images/music/ovochi.jpeg",
    mp3Url: "/music/ovochi.mp3",
    wavUrl: "/music/ovochi.wav",
  },
  {
    trackId: "traffic-lights",
    title: "Світлофор",
    coverSrc: "/images/music/traffic-lights.png",
    mp3Url: "/music/traffic-lights.mp3",
    wavUrl: "/music/traffic-lights.wav",
  },
  {
    trackId: "сhemni-slova",
    title: "Світлофор",
    coverSrc: "/images/music/сhemni-slova.jpeg",
    mp3Url: "/music/сhemni-slova.mp3",
    wavUrl: "/music/сhemni-slova.wav",
  },
  {
    trackId: "bubbles",
    title: "Бульбашки",
    coverSrc: "/images/music/bubbles.jpeg",
    mp3Url: "/music/bubbles.mp3",
    wavUrl: "/music/bubbles.wav",
  },
  {
    trackId: "emotions",
    title: "Емоції",
    coverSrc: "/images/music/emotions.jpeg",
    mp3Url: "/music/emotions.mp3",
    wavUrl: "/music/emotions.wav",
  },
  {
    trackId: "africa",
    title: "Африка",
    coverSrc: "/images/music/africa.jpeg",
    mp3Url: "/music/africa.mp3",
    wavUrl: "/music/africa.wav",
  },
  {
    trackId: "ruhanka",
    title: "Руханка",
    coverSrc: "/images/music/ruhanka.jpeg",
    mp3Url: "/music/ruhanka.mp3",
    wavUrl: "/music/ruhanka.wav",
  },
  {
    trackId: "birthday",
    title: "З Днем народження!",
    coverSrc: "/images/music/birthday.jpeg",
    mp3Url: "/music/birthday.mp3",
    wavUrl: "/music/birthday.wav",
  },
  {
    trackId: "car",
    title: "Машина їде",
    coverSrc: "/images/music/car.jpeg",
    mp3Url: "/music/car.mp3",
    wavUrl: "/music/car.wav",
  },
  {
    trackId: "mykolay",
    title: "Святий Миколай",
    coverSrc: "/images/music/mykolay.jpeg",
    mp3Url: "/music/mykolay.mp3",
    wavUrl: "/music/mykolay.wav",
  },
  {
    trackId: "snowman",
    title: "Це Сніговик",
    coverSrc: "/images/music/snowman.jpeg",
    mp3Url: "/music/snowman.mp3",
    wavUrl: "/music/snowman.wav",
  },
  {
    trackId: "5-birds",
    title: "П'ятеро пташенят",
    coverSrc: "/images/music/5-birds.jpeg",
    mp3Url: "/music/5-birds.mp3",
    wavUrl: "/music/5-birds.wav",
  },
  {
    trackId: "parovoz",
    title: "Паровозик їде, їде",
    coverSrc: "/images/music/parovoz.jpeg",
    mp3Url: "/music/parovoz.mp3",
    wavUrl: "/music/parovoz.wav",
  },
  {
    trackId: "shark",
    title: "Акула",
    coverSrc: "/images/music/shark.jpeg",
    mp3Url: "/music/shark.mp3",
    wavUrl: "/music/shark.wav",
  },
  {
    trackId: "monkeys",
    title: "10 Мавпеняток",
    coverSrc: "/images/music/monkeys.jpeg",
    mp3Url: "/music/monkeys.mp3",
    wavUrl: "/music/monkeys.wav",
  },
  {
    trackId: "money",
    title: "Гроші",
    coverSrc: "/images/music/money.jpeg",
    mp3Url: "/music/money.mp3",
    wavUrl: "/music/money.wav",
  },
  {
    trackId: "love-myself",
    title: "Я люблю себе",
    coverSrc: "/images/music/love-myself.jpeg",
    mp3Url: "/music/love-myself.mp3",
    wavUrl: "/music/love-myself.wav",
  },
  {
    trackId: "ukraine",
    title: "Україна",
    coverSrc: "/images/music/ukraine.jpeg",
    mp3Url: "/music/ukraine.mp3",
    wavUrl: "/music/ukraine.wav",
  },
  {
    trackId: "potyag",
    title: "Їде Потяг",
    coverSrc: "/images/music/potyag.jpeg",
    mp3Url: "/music/potyag.mp3",
    wavUrl: "/music/potyag.wav",
  },
  {
    trackId: "traktor",
    title: "Трактор",
    coverSrc: "/images/music/traktor.jpeg",
    mp3Url: "/music/traktor.mp3",
    wavUrl: "/music/traktor.wav",
  },
  {
    trackId: "vesela-pisenka",
    title: "Весела Пісенька",
    coverSrc: "/images/music/vesela-pisenka.jpeg",
    mp3Url: "/music/vesela-pisenka.mp3",
    wavUrl: "/music/vesela-pisenka.wav",
  },
];